[package]
name = "min-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10"
actix-web = "4"
actix-web-httpauth = "0.8"
mysql_async = "0.31"
sha2 = "0.10"
hex = "0.4"
